### ISSUE TITLE
Release estimation?

### ISSUE THREAD

**Issue by edtjulien** [KangLiao929/MOWA#1]
Hello ;)

Thanks so much for this promising project! I'm very interested to try and use it. I love the idea of a simple and efficient all-in-one toolbox concept like MOWA.

Do you have a release estimated date for the code and pre-trained model?

Best,

**Comment by KangLiao929** [comment]
> Hello ;)
> 
> Thanks so much for this promising project! I'm very interested to try and use it. I love the idea of a simple and efficient all-in-one toolbox concept like MOWA.
> 
> Do you have a release estimated date for the code and pre-trained model?
> 
> Best,

Hi, thanks for your interest! We plan to release the code and pre-trained model of MOWA in one or two months, regardless of whether it is accepted by the paper publisher. Please stay tuned.

**Comment by edtjulien** [comment]
Hey hey. Any update about code release? ❤️

**Comment by KangLiao929** [comment]
> Hey hey. Any update about code release? ❤️

Hey, I will release the code this week!

**Comment by edtjulien** [comment]
That's my best weekend news!

**Comment by KangLiao929** [comment]
> That's my best weekend news!

Codes and weights have been released.
